module.exports = {
  UNSPLASH_APPLICATION_ID: process.env.UNSPLASH_APPLICATION_ID,
  UNSPLASH_SECRET: process.env.UNSPLASH_SECRET,
  UNSPLASH_CALLBACK_URL: process.env.UNSPLASH_CALLBACK_URL,
  MONGO_URI: process.env.MONGO_URI,
  COOKIE_KEY: process.env.COOKIE_KEY,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
  CORS_URL: process.env.CORS_URL
};
